### ISSUE TITLE
Add a search to the docs

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/documentation#10]
Based on this documentation https://v2.docusaurus.io/docs/search we should try to integrate a search function within our docs.

**Comment by fuhrmeistery** [comment]
Do we want to use the Service provided by Algolia? If so, is there already an application pending?

**Comment by fuhrmeistery** [comment]
The application is currently in Progress

**Comment by twwd** [comment]
What about a local search index and JS search with lunar?
- https://github.com/lelouch77/docusaurus-lunr-search
- https://github.com/cmfcmf/docusaurus-search-local
- https://github.com/easyops-cn/docusaurus-search-local

**Comment by twwd** [comment]
Closed with #101
