### ISSUE TITLE
 Check docs for all scanners for correctness: nuclei

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/documentation#166]
Part of the effort to sanity-check all documentation.

## Scanner Sanity-Check:
- [x] Sanity Check if the existing documentation is understandable and useful for you as a (first time) user
- [x] Ensure the general chart/scanner description is up to date and consistent to other scanners
   * `./scanner/NAME/.helm-docs.gotmpl -> {{- define "extra.chartAboutSection" -}}`
- [x] Ensure the baseline scanner configuration is up to date and consistent to other scanners
   * `./scanner/NAME/.helm-docs.gotmpl -> {{- define "extra.scannerConfigurationSection" -}}`
- [x] Ensure there is at minimum one scan example with the following files:
   * Example Scan File: `./scanner/NAME/examples/EXAMPLE-NAME/scan.yaml`
   * Example Scan Result File: `./scanner/NAME/examples/EXAMPLE-NAME/findings.yaml`
- [x] Ensure the docs files are generated correct and are up to date (sometimes the automated helm-docs update via SCB-Bot failed to update the docs correctly)
   * `./scanner/NAME/readme.md`
   * `./scanner/NAME/docs/README.ArtifactHub.md`
   * `./scanner/NAME/docs/README.DockerHub-Parser.md`
   * Optional, only if a dedicated scanner image is defined:`./scanner/NAME/docs/README.DockerHub-Scanner.md`
   
## Additional Context:
- SCB Scanner Documentation (based on the above markdown files): https://docs.securecodebox.io/docs/scanners
- SCB DockerHub Images (with description based on docs for each image): https://hub.docker.com/u/securecodebox/
- SCB Artifact Helm Charts: https://artifacthub.io/packages/search?org=securecodebox

**Comment by Ilyesbdlala** [comment]
Nuclei seems to encounter an issue when installing locally. The Nuclei scanner attempts to update its templates after install. In doing so, the Persistent Volume Claim `nuclei-content-claim` fails to be provisioned correctly. The corresponding pod hangs in the "pending" state. When examining, we find the following error message 
![image](https://user-images.githubusercontent.com/62256235/143037742-b9b69bf8-47d8-431d-8902-61414cc92e6d.png)
It should also be noted that Nuclei currently has no integration tests implemented.

**Comment by malexmave** [comment]
Adding to the above: nuclei can be installed without using a PVC by using `helm upgrade --install nuclei secureCodeBox/nuclei --set="nucleiTemplateCache.enabled=False"`. This will allow it to install and start up. However, trying to scan a website will result in an error about having no templates, and telling it to update the templates (`-ut`) will lead to it updating the templates, but ignoring the rest of the command and not performing a scan.

This can probably be solved using an init container, if the use of PVCs is not desired / possible. In general, there are some parallels to trivy, which has the same issues: Needing to update some data from the web, which is rate limited, but being unable to share it between multiple instances. Solving this issue for one of the scanners should technically be able to solve it for both, and it would be good to solve it in the same way, if possible.
