### ISSUE TITLE
Improve Naming of the ADRs in the sidebar

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/documentation#207]
Currently the ADRs are shown in the sidebar as "adr_0001", without any context. We should update them to be "ADR-0001: [short summary]". This can probably be done by changing the ADR markdown files and adding the "title" attribute, similar to the markdown files in this repo.

**Comment by Weltraumschaf** [comment]
I would say: Won't do bc the titles are way too long for the sidebar.
