### ISSUE TITLE
Add architecture documentation

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/documentation#208]
The documentation currently has a menu point for architecture, but it does not have any information in it. We should produce a short overview of the architecture, potentially based on one of the old blog posts, to explain how the system works.

**Comment by sanmai-NL** [comment]
@malexmave Is anyone currently working on this?
We may have a taker on our team.

**Comment by malexmave** [comment]
We don't have anyone actively working on this, so feel free :)

**Comment by Weltraumschaf** [comment]
Moved as planned in progress bc we decided in one of our last plannings that we merge @Stijn-FE work and evolve from that starting point.
