### ISSUE TITLE
Blog-Post: post-Mortem Log4J

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/documentation#213]
We would like to share our experience to hunt for Log4Shell vulnerabilites based on SCB (DAST & SAST). Therefore we come up with a new blog post.

- [ ] check if iteratec reference is fine @rseedorff 
- [ ] Add YAML examples (playbook)
       - [ ] Nuclei
       - [ ] Semgrep

**Comment by Ilyesbdlala** [comment]
Closed by #226: Blogpost found [here](https://www.securecodebox.io/blog/2022/01/18/log4shell).
