### ISSUE TITLE
Make Category Overview Page Tiles Prettier

### ISSUE THREAD

**Issue by RamiSouai** [secureCodeBox/documentation#239]
PR #206 introduced overview pages for categories. Currently the description used for the tiles is the first line in the pages' md file, leading to  unfitting descriptions (See Screenshot).  

![image](https://user-images.githubusercontent.com/68519768/159240281-b4a08661-e8ad-46d7-9f34-ec825cde3df7.png)

On top of this, the 📄️ Emoji at the start of each tile's title is cut at the bottom. 

**AKs:**
- The tiles have a fitting description under the titles
- The emojis are no longer cut at the bottom

**Additional Information:**
Examining the style sheets, we see that disableing the overflow fixes the emoji issue. 
![image](https://user-images.githubusercontent.com/68519768/159245039-3da27ab9-acb4-44ca-a8a6-45af5cf75800.png)
![image](https://user-images.githubusercontent.com/68519768/159245087-cf619605-6ce6-43d3-8ba3-6e16a26b545d.png)

**Comment by Weltraumschaf** [comment]
Already fixed.
