### ISSUE TITLE
Add a table of content for architecture descision records

### ISSUE THREAD

**Issue by SebieF** [secureCodeBox/documentation#278]
As a secureCodeBox developer, I would like to have a quick overview about architectural decision records in the documentation to save time when searching for a specific ADR. To realize this, one could add a table of contents, probably at [this page](https://www.securecodebox.io/docs/architecture/architecture_decisions/).
It would also probably be good to briefly describe the ADR in one sentence there.

**Comment by Weltraumschaf** [comment]
Someone did this by accident 😂
