### ISSUE TITLE
Include security.md in documentation website

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/documentation#301]
# Problem

The security.md from our primary repo is currently not included in the website which makes the information in it hard to find for users.

https://github.com/secureCodeBox/secureCodeBox/blob/main/SECURITY.md

# Suggested Solution

Add a "Security" section to the sidebar and render the security.md out to it's own page.

## Alternative Solution

If that does not work, we can also add a direct link to the github webpage with the security.md or add a new static article in the docs repo linking to it.

**Comment by martinyis** [comment]
Hey, it looks like an interesting problem. Could you assign it to me?

**Comment by Weltraumschaf** [comment]
Hi @martinyis 👋

Nice that you want to contribute ❤️

Please read the CONTRIBUTING.md and sign the DCO before contributing.

**Comment by martinyis** [comment]
Could you navigate me to your sidebar file, because the code is a bit complicated?

**Comment by Weltraumschaf** [comment]
Its [here](https://github.com/secureCodeBox/documentation/blob/main/sidebars.json). But you do not need to modify this. Side bar is generated by the `_category_.json` files. E.g. for the API category [here](https://github.com/secureCodeBox/documentation/blob/main/docs/api/_category_.json).

**Comment by Weltraumschaf** [comment]
Do we remove the security.md in the securecodeBox repo? Or add a link to the website? We should not maintain both.
