### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by JohannesZahn** [secureCodeBox/documentation#64]
The page https://docs.securecodebox.io/docs/api/crds/scan/ refers to https://docs.securecodebox.io/docs/crds/cascading-rule which gives a 404 Error.

**Comment by J12934** [comment]
@JohannesZahn oh good catch. 👍
Can you send a quick pr fixing the links?

**Comment by JohannesZahn** [comment]
I just sent the PR
