### ISSUE TITLE
Link in ATOM Feed is broken

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/documentation#7]
The link to the first post (https://securecodebox.io/blog/2020/09/08/blinmaker) results in 404.

The URL misses the `docs.` subdomain. The URL should be https://docs.securecodebox.io/blog/2020/09/08/blinmaker

**Comment by J12934** [comment]
@dpatanin can this be closed?

**Comment by J12934** [comment]
Also is the location of the feeds documented somewhere? Or are there established defaults to where the are located that this isn't required?

**Comment by dpatanin** [comment]
The issue was that the link of the project's config was pointing to https://securecodebox.io rather than https://docs.securecodebox.io. The feed  itself was working properly and pointing to the default location.
