### ISSUE TITLE
📚Add a dedicated Installation section with different target 🎯 environments

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/documentation#70]
Add install instructions for different environments like:
- [ ] Bin/install / Helm ⛑ 
- [ ] Kustomize

- [ ] Vagrant
- [ ] Minikube
- [ ] Docker for Desktop
- [ ] Rancher v2
- [ ] K3S / K0S
- [ ] GKE / AKS / EKS

**Comment by Weltraumschaf** [comment]
We have [some documentation](https://docs.securecodebox.io/docs/getting-started/installation) about this topic, but not exhaustive. IMO we should file new issues for each dedicated environment which requires dedicated documentation.
