### ISSUE TITLE
📚 Add a dedicated “Testing” section and explain the project test strategy

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/documentation#71]
As contributer i would like to to know how the test strategy of the project is implemented, how to use and extend it.

**Acceptance Criteria**

* New _Test Concept Guide_ is documented here: https://docs.securecodebox.io/docs/contributing/test-concept
* It is documented where to implement/find unit-tests, integration-tests.
* It is documented how to use/start unit-tests, integration-tests with make

** further informations**

Reference to common patterns and best practice strategies like: https://martinfowler.com/articles/practical-test-pyramid.html

** topics to cover** 

- [x] Unit Tests for core components like the operator (Go tests)
  - [x] Operator #250 
- [x] Unit Tests for secureCodeBox modules like sdk, hooks, scanner... (jest an pytest)
  - [x] Scanners #250 
  - [x] Hooks  #258 
- [x] Integration Tests 
  - [x] Scanners #250 
  - [x] Hooks #258 
- [ ] Introduction and Guideline to the Test Concept (reference to fowler) - What do we use (unit, integration), what is important (speed) https://github.com/secureCodeBox/documentation/pull/259

**Comment by Weltraumschaf** [comment]
Here are the promised links to the talks about testing from @marcphilipp: [Produktive Tests](https://speakerdeck.com/marcphilipp/produktive-tests-german) (German). There is also an [abstract](https://www.softwerkskammer.org/activities/ka-treffen-100) with some good links:

* [Test Pyramid Fowler](https://martinfowler.com/bliki/TestPyramid.html) (must read)
* [Integrated Tests Are A Scam](https://blog.thecodewhisperer.com/permalink/integrated-tests-are-a-scam)
* [Lean Testing or Why Unit Tests are Worse than You Think](https://medium.com/@eugenkiss/lean-testing-or-why-unit-tests-are-worse-than-you-think-b6500139a009)
* [Test Desiderata](https://medium.com/@kentbeck_7670/test-desiderata-94150638a4b3)
*

**Comment by marcphilipp** [comment]
@Weltraumschaf Nice to see my little talk mentioned here! 😊
