### ISSUE TITLE
Autogenerate the Sidebar

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/documentation#92]
At the moment we have a static sidebar and there we add the scanner and hooks documentation via build script. But this concept is not sufficient any more for the use case to add the ADRs and other docs from the main repository.

**Comment by dpatanin** [comment]
One fundamental quesiton is, whether and how much documentation will be pulled from a different repository.
Pulling from another source would most certainly require a build script of some sorts, at least for the documents themselves. 
The sidebar however depends highly on:
- desired structure
- adaptability/scalability
- ease of use

Regardless of the source of documents, it's always possible to handwrite the sidebar (the "default" way of docusaurus).
Another strategy could be fully autogenerate it, either by docusaurus itself or by a custom script.
The difficult part is a partially automated construction as it requires adding generated parts to a written sidebar. The simplest, and so far implemented, way of concatinating the generated parts at a specified section met its limits with the ADRs. It does not allow for putting remote documentation into specific locations as the requirements for the ADRs showed, thus demanding a different solution. 

The ideal use would be a file, e.g. a simple configuration file, in which a source location can be specified and a destination. The challenge is: How can we build a sidebar containing local and remotely generated files, which also automatically is able to put those files into a specified category which may or may not exist already?
